"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:43:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

"Indicates what fields are available at the top level of a query operation."
type Query {
    "Find a single user by an identifying attribute."
    user(
      "Search by primary key."
      id: ID @eq @rules(apply: ["prohibits:email", "required_without:email"])

      "Search by email address."
      email: String @eq @rules(apply: ["prohibits:id", "required_without:id", "email"])
    ): User @find

    "List multiple users."
    users(
      "Filters by name. Accepts SQL LIKE wildcards `%` and `_`."
      name: String @where(operator: "like")
    ): [User!]! @paginate(defaultCount: 10)

    film(id: ID! @eq): Film! @find
    films(
        keyword: String @where(key: "title", key: "description", operator: "like"),
        release_year: Int @where(key: "release_year", operator: ">="),
        length_min: Int @where(key: "length", operator: ">="),
        length_max: Int @where(key: "length", operator: "<="),
    ): [Film!]! @paginate(defaultCount: 10)

    me: User @auth
}

type CreateCriticInput {
    score: Int!
    comment: String
    film: CreateAFilmBelongsTo!
}

input CreateAFilmBelongsTo {
    connect: ID
}

type Mutation {
    createCritic(input: CreateCriticInput! @spread): Critic! @create @guard @inject(context: "user.id", name: "user_id")
}

"Account of a person who uses this application."
type User {
    "Unique primary key."
    id: ID!

    first_name: String!
    last_name: String!

    "Unique email address."
    email: String!

    "When the email was verified."
    email_verified_at: DateTime

    "When the account was created."
    created_at: DateTime!

    "When the account was last updated."
    updated_at: DateTime!

    critics: [Critic] @hasMany
}

type Film {
    id: ID!
    title: String!
    release_year: Int
    length: Int
    description: String
    rating: String
    special_features: [String]
    image: String
    language: Language @belongsTo
    critics: [Critic] @hasMany
    actors: [Actor] @belongsToMany
}

type Critic {
    id: ID!
    score: Int
    comment: String
    user: User @belongsTo
    film: Film @belongsTo
}

type Language {
    id: ID!
    name: String!
    films: [Film] @hasMany
}

type Actor {
    id: ID!
    last_name: String!
    first_name: String!
    birthdate: DateTime
    films: [Film] @belongsToMany
}
